Base/Base/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('TC.urls')),
    path('', include ('users.urls')),
    path('chat/', include('chat.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Base/TC/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import Send
urlpatterns = [
     path('', views.home, name='home' ),
     path('registro/', views.registro, name='registro'),
     path('nosotros/', views.nosotros, name='nosotros'),
     path('producto/', views.pp, name='producto'),
     path('login/', views.login, name='login'),
     path('cerrar-sesion/', views.cerrarSesion, name='cerrar_sesion'),
     path('perfil/', views.perfil, name='perfil'),
     path('edperfil/', views.edperfil, name='edperfil'),
     path('mis_publicaciones/', views.publicaciones, name='publicaciones'),
     path('Post_producto/', views.pp, name='post_producto'),
     path('publicar/', views.publicar_producto, name='publicar_producto'),
     path('publicacion/', views.publicacion, name='publicacion'),
     path('detalle_producto/<int:id>', views.detalle_producto, name='detalle_producto'),
     path('cambiar_estado_producto/<int:producto_id>/', views.cambiar_estado_producto, name='cambiar_estado_producto'),
     path('editar_producto/<int:id>', views.vista_editar_producto, name='vista_editar_producto'),
     path('editar_productos/<int:producto_id>/', views.editar_producto, name="editar_productos"),
     path('perfil_publico/<int:user_id>/', views.perfil_publico, name='perfil_publico'),
     path('expresar_interes/<int:producto_id>/', views.expresar_interes, name='expresar_interes'),
     path('notificaciones/', views.ver_notificaciones, name='ver_notificaciones'),
     path('contador_notificaciones/', views.contador_notificaciones, name='contador_notificaciones'),
     path('eliminar-notificacion/<int:notificacion_id>/', views.eliminar_notificacion, name='eliminar_notificacion'),
     path('eliminar-todas-notificaciones/', views.eliminar_todas_notificaciones, name='eliminar_todas_notificaciones'),  # Nueva ruta para eliminar todas las notificaciones
     path('producto/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
     path('valoracion/', views.valoracion, name='valoracion'),
     path('send/', Send.as_view(), name='send_email'),
     path('nuevapss/<uidb64>/<token>/', views.passn, name='nuevapss'),

    ]    

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Base/TC/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from users.models import User
import os
from django.conf import settings
from django.core.exceptions import ValidationError
#Define clase categoría con su id y su nombre
class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return f"{self.id} ({self.nombre})"
    
 #Define clase condición con su id y el tipo de condición
class Condicion(models.Model):
    id = models.AutoField(primary_key=True)
    condicion = models.CharField(max_length=200)
    
    def __str__(self):
        return f"{self.id} ({self.condicion})"
 
 #Define clase imagen con su id y la dirección de la imagen
class GaleriaImagenes(models.Model):
    id = models.AutoField(primary_key=True)
    imagen = models.ImageField(upload_to='productos', null=True)
    
    def __str__(self):
        return f"{self.id} {self.imagen}"

    def delete(self, *args, **kwargs):
        if self.imagen:
            if os.path.isfile(self.imagen.path):
                os.remove(self.imagen.path)
        super().delete(*args, **kwargs)

 #Define clase producto con todo lo que conlleva 
class Producto(models.Model):

    DISPONIBLE = 'DISP'
    SOLICITADO = 'SOL'
    INTERCAMBIADO = 'INT'
    
    ESTADO_CHOICES = [
        (DISPONIBLE, 'Disponible'),
        (SOLICITADO, 'Solicitado'),
        (INTERCAMBIADO, 'Intercambiado'),
    ]

    id = models.AutoField(primary_key=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    condicion = models.ForeignKey(Condicion, on_delete=models.CASCADE)
    imagen = models.ForeignKey(GaleriaImagenes, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    descripcion = models.CharField(max_length=500)
    fecha = models.DateField()
    estado = models.CharField(
        max_length=4,
        choices=ESTADO_CHOICES,
        default=DISPONIBLE,
    )
    
    def __str__(self):
        return f"{self.nombre} ({self.id})"

    def delete(self, *args, **kwargs):
        self.imagen.delete()
        super().delete(*args, **kwargs)


    #para comentar todo precionar ctrl + k + c 
    #para descomentar preciona ctrl + k + u




class Notificacion(models.Model):
    TIPOS_NOTIFICACION = (
        ('nuevo_producto', 'Nuevo Producto'),
        ('interes_producto', 'Interés en Producto'),
    )

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=20, choices=TIPOS_NOTIFICACION)
    mensaje = models.CharField(max_length=200)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True, blank=True)
    leida = models.BooleanField(default=False)  # Nuevo campo para indicar si la notificación ha sido leída

    def __str__(self):
        return f"{self.usuario} ({self.tipo}) - {self.mensaje}"   

 
class Valoracion(models.Model):
    usuario_evaluado = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='valoraciones_recibidas', on_delete=models.CASCADE)
    usuario_evaluador = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='valoraciones_realizadas', on_delete=models.CASCADE)
    puntuacion = models.IntegerField()
    comentario = models.TextField(blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario_evaluado.full_name} - Puntuación: {self.puntuacion}"

    def clean(self):
        if self.usuario_evaluado == self.usuario_evaluador:
            raise ValidationError("Un usuario no puede evaluarse a sí mismo.")
        if self.puntuacion < 1 or self.puntuacion > 5:
            raise ValidationError("La puntuación debe estar entre 1 y 5.")

    def save(self, *args, **kwargs):
        self.full_clean()  # Ensure validations are called before saving
        super().save(*args, **kwargs)
    
# class HistorialActividad(models.Model):
#     usuario = models.ForeignKey(User, on_delete=models.CASCADE)
#     actividad = models.CharField(max_length=200)
#     fecha = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         texto = "{0} ({1})"
#         return texto.format(self.usuario)

# class ListaDeseos(models.Model):
#     usuario = models.ForeignKey(User, on_delete=models.CASCADE)
#     nombre_elemento = models.CharField(max_length=100)
#     descripcion = models.TextField(blank=True, null=True)

#     def __str__(self):
#         texto = "{0} ({1})"
#         return texto.format(self.usuario)

Base/TC/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.detail import DetailView
from .models import   Producto, Categoria, Condicion, GaleriaImagenes , Notificacion, Valoracion
from users.models import Region, Comuna , Pais
from django.contrib.auth import logout, get_user_model
from django.utils import timezone
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
#from django.contrib.auth.models import User 
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.
from users.models import User
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.conf import settings
from django.views import View

from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode

def registro(request):
    regiones = Region.objects.all()
    comunas = Comuna.objects.all()
    return render(request, 'registro.html', {'regiones': regiones, 'comunas': comunas})

def nosotros(request):
    return render(request, 'nosotros.html')

@login_required
def pp(request):
    categorias = Categoria.objects.all()
    condiciones = Condicion.objects.all()
    return render(request, 'Post_producto.html', {'categorias': categorias, 'condiciones': condiciones})


def cerrarSesion(request):
    logout(request)
    return redirect('/')

def login(request):
    return render(request, 'login.html')

@login_required
def perfil(request):
    regiones = Region.objects.all()
    comunas = Comuna.objects.all()
    return render(request, 'perfil.html', {'regiones': regiones, 'comunas': comunas})

@login_required
def edperfil(request):
    regiones = Region.objects.all()
    comunas = Comuna.objects.all()
    return render(request, 'edit_perfil.html', {'regiones': regiones, 'comunas': comunas})

@login_required
def publicaciones(request):
    # Filtrar productos por el usuario logueado
    productos_usuario = Producto.objects.filter(usuario=request.user)
    
    # Obtener todos los usuarios
    users = User.objects.all()  # Utiliza el modelo de usuario correcto
    
    # Renderizar la plantilla con los datos
    return render(request, 'mis_publicaciones.html', {'productos': productos_usuario, 'users': users})


def perfil_publico(request, user_id):
    usuario = get_object_or_404(User, id=user_id)
    producto = get_object_or_404(Producto, id=user_id)
    valoraciones = Valoracion.objects.filter(usuario_evaluado=usuario)
    productos_del_usuario = Producto.objects.filter(usuario=usuario)
    return render(request, 'perfilpublico.html', {
        'producto': producto,
        'usuario': usuario,
        'Productos': productos_del_usuario,
        'valoraciones': valoraciones,
        })


def publicacion(request):
    categoria_id = request.GET.get('categoria', None)
    condicion_id = request.GET.get('condicion', None)
    estado = request.GET.get('estado', None)

    query = request.GET.get('q', None)  # Obtén el término de búsqueda del query string

    if categoria_id:
        productos = Producto.objects.filter(categoria_id=categoria_id).exclude(estado=Producto.INTERCAMBIADO)
    elif condicion_id:
        productos = Producto.objects.filter(condicion_id=condicion_id).exclude(estado=Producto.INTERCAMBIADO)
    elif estado:
        productos = Producto.objects.filter(estado=estado).exclude(estado=Producto.INTERCAMBIADO)
    else:
        productos = Producto.objects.exclude(estado=Producto.INTERCAMBIADO)

    if query:
        productos = productos.filter(nombre__icontains=query)  # Filtra por nombre del producto (ajusta según tus necesidades)

    categorias = Categoria.objects.all()
    condiciones = Condicion.objects.all()
    estados = Producto.ESTADO_CHOICES
    context = {
        'Productos': productos,
        'categorias': categorias,
        'condiciones': condiciones,
        'estados': estados,
        'categoria_seleccionada': categoria_id,
        'condicion_seleccionada': condicion_id,
        'estado_seleccionado': estado,
        'query': query,
    }
    return render(request, 'publicaciones.html', context)

def home(request):
    productos = Producto.objects.exclude(estado=Producto.INTERCAMBIADO)
    return render(request, 'principal.html', {'Productos': productos})

@login_required
def publicar_producto(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        categoria_id = request.POST.get('categoria')
        condicion_id = request.POST.get('condicion')
        imagen_archivo = request.FILES.get('imagen')
        descripcion = request.POST.get('descripcion')

        # buscando en la base de datos categorias y condiciones pre pobladas
        categoria = Categoria.objects.get(id=categoria_id)
        condicion = Condicion.objects.get(id=condicion_id)

        # agregando nueva imagen
        nueva_imagen = GaleriaImagenes.objects.create(imagen=imagen_archivo)
        
        # Crear un nuevo objeto de usuario utilizando el gestor de usuarios personalizado
        nuevo_producto = Producto.objects.create(
            categoria = categoria,
            condicion = condicion,
            imagen = nueva_imagen,
            nombre = nombre,
            usuario = request.user,
            descripcion = descripcion,
            fecha=timezone.now()
        )
        Notificacion.objects.create(
            usuario=request.user,
            mensaje=f'Se ha añadido un nuevo producto: {nuevo_producto.nombre}',
            producto=nuevo_producto
        )
        # Redirigir al usuario a la página que desees después del registro
        return redirect('/')  # Por ejemplo, redirigir a la página de inicio
    
    # Si el método de solicitud no es POST o si hay algún error en el proceso, renderizará el formulario de registro.
    categorias = Categoria.objects.all()
    condiciones = Condicion.objects.all()
    return render(request, 'Post_producto.html', {'categorias': categorias, 'condiciones': condiciones})



def detalle_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    return render(request, 'detalle_producto.html', {'producto': producto})

def cambiar_estado_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    if request.method == 'POST':
        nuevo_estado = request.POST.get('nuevo_estado')
        if nuevo_estado in [Producto.DISPONIBLE, Producto.SOLICITADO, Producto.INTERCAMBIADO]:
            producto.estado = nuevo_estado
            messages.success(request, f'Estado de {producto.nombre} cambiado correctamente.')
            producto.save()

            # Obtener el ID del usuario seleccionado para el intercambio desde el formulario
            usuario_intercambio_id = request.POST.get('usuario_intercambio')
            if usuario_intercambio_id:
                usuario_intercambio = get_object_or_404(User, id=usuario_intercambio_id)
                # Crear y guardar la notificación
                mensaje = f'Felicidades por realizar un trueke con {request.user.name}! ¿Deseas dejar algún comentario? ' \
                          f'<a href="../valoracion">Haz clic aquí</a>'
                Notificacion.objects.create(
                    usuario=usuario_intercambio,
                    mensaje=mensaje,
                    producto=producto
                )

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required
def vista_editar_producto(request, id):
    categorias = Categoria.objects.all()
    condiciones = Condicion.objects.all()
    producto = get_object_or_404(Producto, id=id)
    return render(request, 'editar_producto.html', {'producto': producto, 'categorias': categorias, 'condiciones': condiciones})

def editar_producto(request, producto_id):
    # Obtener el producto que se va a editar
    producto = get_object_or_404(Producto, id=producto_id)

    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        categoria_id = request.POST.get('categoria')
        condicion_id = request.POST.get('condicion')
        imagen_archivo = request.FILES.get('imagen')
        descripcion = request.POST.get('descripcion')
        nuevo_estado = request.POST.get('nuevo_estado')

        # Buscar en la base de datos categorías y condiciones pre pobladas
        categoria = Categoria.objects.get(id=categoria_id)
        condicion = Condicion.objects.get(id=condicion_id)

        # Actualizar la imagen si se ha subido una nueva
        if imagen_archivo:
            nueva_imagen = GaleriaImagenes.objects.create(imagen=imagen_archivo)
            producto.imagen = nueva_imagen

        # Actualizar los demás campos del producto
        producto.categoria = categoria
        producto.condicion = condicion
        producto.nombre = nombre
        producto.descripcion = descripcion
        producto.fecha_actualizacion = timezone.now()

        # Cambiar el estado del producto si se ha seleccionado uno nuevo
        if nuevo_estado:
            producto.estado = nuevo_estado

        producto.save()

        # Redirigir al usuario a la página que desees después de la edición
        return redirect('/')  # Por ejemplo, redirigir a la página de inicio
    
#Funciones


def expresar_interes(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    if request.method == 'POST':
        mensaje_interes = request.POST.get('mensaje_interes', '')

        # Crear una nueva notificación de interés en producto
        Notificacion.objects.create(
            usuario=producto.usuario,

Base/TC/templates/Post_producto.html
{% extends "./base.html" %}

{% block body %}
{% load static %}

<br><br> 

<link href="{% static 'style/styleregistro.css' %}" rel="stylesheet" type="text/css">

<div class="container">
    <form method="post" enctype="multipart/form-data" action="{% url 'publicar_producto' %}" class="form">
        {% csrf_token %}
        <h2 class="title">Publicar Producto</h2>
        
        <!-- Nombre -->
        <div class="inputContainer">
            <input type="text" id="nombre" name="nombre" class="input" placeholder=" " required>
            <label for="nombre" class="label">Nombre</label>
        </div>
        
        <!-- Categoría -->
        <div class="inputContainer">
            <select id="categoria" name="categoria" class="input" required>
                <option value="" disabled selected></option>
                {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
            <label for="categoria" class="label">Categoría</label>
        </div>
        
        <!-- Condición -->
        <div class="inputContainer">
            <select id="condicion" name="condicion" class="input" required>
                <option value="" disabled selected></option>
                {% for condicion in condiciones %}
                    <option value="{{ condicion.id }}">{{ condicion.condicion }}</option>
                {% endfor %}
            </select>
            <label for="condicion" class="label">Condición</label>
        </div>
        
        <!-- Imagen -->
        <div class="inputContainer">
            <input type="file" id="imagen" name="imagen" class="input" accept="image/*" required>
            <label for="imagen" class="label">Imagen</label>
        </div>
        
        <!-- Descripción -->
        <div class="inputContainer">
            <textarea id="descripcion" name="descripcion" class="input" placeholder=" " required></textarea>
            <label for="descripcion" class="label">Descripción</label>
        </div>
        
        <!-- Botón de envío -->
        <input type="submit" class="submitBtn" value="Publicar">
    </form>
</div>

{% endblock %}

Base/TC/templates/detalle_producto.html
{% extends "./base.html" %}
{% load static %}
{% block body %}
{% if messages %}
<br>
<div class="alert alert-success text-center" role="alert">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
<link href="{% static 'style/styledetalleproducto.css' %}" rel="stylesheet" type="text/css">
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="product-card card mb-4">
                <div class="product-img-container">
                    <img src="{{ producto.imagen.imagen.url }}" alt="{{ producto.nombre }}" class="product-img img-fluid rounded">
                </div>
                <div class="card-body">
                    <h5 class="product-title">{{ producto.nombre }}</h5>
                    <p class="product-description">{{ producto.descripcion }}</p>
                    <p><strong>Categoría:</strong> {{ producto.categoria.nombre }}</p>
                    <p><strong>Condición:</strong> {{ producto.condicion.condicion }}</p>
                    <p><strong>Estado:</strong> {{ producto.get_estado_display }}</p>
                    <p><strong>Publicado por:</strong> <a href="{% url 'perfil_publico' user_id=producto.usuario.id %}">{{ producto.usuario.name }} {{ producto.usuario.lastname }}</a></p>
                    <p><strong>Comuna de origen:</strong> {{ producto.usuario.comuna.nombre }}</a></p>
                    <a href="{% url 'publicacion' %}" class="btn btn-secondary">Volver a la lista de productos</a>
                        <br>
                    <form method="POST" action="{% url 'expresar_interes' producto_id=producto.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="mensaje_interes" value="Hola! Me interesa este producto"></input>
                        <button type="submit" class="btn btn-primary mt-2">Me interesa</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
    const imgContainer = document.querySelector('.product-img-container');
    const img = document.querySelector('.product-img');

    imgContainer.addEventListener('mousemove', function(e) {
        const rect = imgContainer.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        const xPercent = (x / rect.width) * 100;
        const yPercent = (y / rect.height) * 100;
        img.style.transformOrigin = `${xPercent}% ${yPercent}%`;
        img.style.transform = 'scale(1.5)';
    });

    imgContainer.addEventListener('mouseleave', function() {
        img.style.transformOrigin = 'center center';
        img.style.transform = 'scale(1)';
    });
});
</script>
{% endblock %}

Base/TC/templates/login.html
{% extends "./base.html" %}
{% load static %}

{% block body %}
<link href="{% static '../static/style/styleregistro.css' %}" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<br><br><br>
<body>
    <div class="container">
        <form action="/iniciarSesion/" class="form" id="loginForm" method="POST">
          {% csrf_token %}
          {% if error_message %}
              <p>{{ error_message }}</p>
          {% endif %}
          
          <h2 class="title">Iniciar Sesión</h2>
      
          <div class="inputContainer">
            <input type="email" id="txtCorreo" name="txtCorreo" class="input" placeholder=" " required>
            <label for="txtCorreo" class="label"> Correo Electrónico</label>
          </div>
      
          <div class="inputContainer">
            <input type="password" id="txtPassword" name="txtPassword" class="input" placeholder=" " required>
            <label for="txtPassword" class="label"> Contraseña</label>
          </div>
      
          <input type="submit" class="submitBtn" value="Iniciar Sesión">
        </form>
        <a class="text-primary" href="{% url 'send_email' %}">Olvidaste tu Contraseña ?</a>
      </div>
</body>
</html>
{% endblock %}

Base/TC/templates/mis_publicaciones.html
{% extends "./base.html" %}

{% block body %}
{% load static %}
<link href="{% static 'style/styleproductos.css' %}" rel="stylesheet" type="text/css">
<br>
{% if messages %}
<br>
<div class="alert alert-success text-center" role="alert">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="title">Mis Publicaciones</h1>
        <a class="btn btn-primary" href="{% url 'post_producto' %}" role="button">Nueva Publicación</a>
    </div>
    <div class="row">
        {% for producto in productos %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    {% if producto.imagen %}
                        <img src="{{ producto.imagen.imagen.url }}" alt="{{ producto.nombre }}" class="card-img-top"  style="max-height:200px; object-fit: cover;">
                    {% else %}
                        <img src="{% static 'placeholder_image.jpg' %}" alt="Placeholder" class="card-img-top"  style="max-height:200px; object-fit: cover;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ producto.nombre }}</h5>
                        <p class="card-text">{{ producto.descripcion }}</p>
                        <p class="card-text">{{ producto.get_estado_display }}</p>
                        <a href="{% url 'vista_editar_producto' producto.id %}" class="btn btn-primary">Ver</a>

                        <br><br>

                        <!-- Botón para abrir modal de cambio de estado -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal-{{ producto.id }}">
                            Cambiar estado
                        </button>

                        <!-- Modal para cambiar estado del producto -->
                        <div class="modal fade" id="exampleModal-{{ producto.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Cambiar estado</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form method="post" action="{% url 'cambiar_estado_producto' producto.id %}">
                                            {% csrf_token %}
                                            <div class="mb-3">
                                                <label for="estado-{{ producto.id }}" class="form-label">Estado</label>
                                                <select name="nuevo_estado" id="estado-{{ producto.id }}" class="form-select">
                                                    <option value="DISP" {% if producto.estado == "DISP" %}selected{% endif %}>Disponible</option>
                                                    <option value="SOL" {% if producto.estado == "SOL" %}selected{% endif %}>Solicitado</option>
                                                    <option value="INT" {% if producto.estado == "INT" %}selected{% endif %}>Intercambiado</option>
                                                </select>
                                            </div>
                                            <label>Realizaste el intercambio con algún usuario?</label>
                                            <select name="usuario_intercambio" class="form-select">
                                                <option value="">Ninguno</option>
                                                {% for user in users %}
                                                    {% if user != request.user %}
                                                        <option value="{{ user.id }}">{{ user.name }} {{ user.lastname }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="submit" class="btn btn-primary">Actualizar</button>
                                            </div>
                                        </form> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block scripts %}

{% endblock %}

Base/TC/templates/valoracion.html
{% extends "./base.html" %}

{% block body %}
{% load static %}
<br>
<center><h1>Valoración de Trueque</h1></center>

<link href="{% static '../static/style/styleregistro.css' %}" rel="stylesheet" type="text/css">
<!-- Mostrar nombre completo del usuario que envió la notificación -->


<!-- Formulario para dejar comentario y puntuación -->
<div class="container">
    <form method="post" action="{% url 'valoracion' %}">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_usuario_evaluado">Usuario a evaluar:</label>
            <select id="id_usuario_evaluado" name="usuario_evaluado_id" class="form-control" required>
                <option value="">Selecciona un usuario</option>
                {% for usuario in usuarios_disponibles %}
                <option value="{{ usuario.id }}">{{ usuario.name }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="id_puntuacion">Puntuación (1-5):</label>
            <input type="number" id="id_puntuacion" name="puntuacion" min="1" max="5" class="form-control" required>
        </div>
        
        <div class="form-group">
            <label for="id_comentario">Comentario:</label>
            <textarea id="id_comentario" name="comentario" rows="4" class="form-control"></textarea>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Enviar Valoración</button>
    </form>
</div>
{% endblock %}